spring.application.name=librarycontrolsystem
spring.datasource.password=231@Eu11er
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/librarysystem
spring.jpa.hibernate.ddl-auto=create